cask_args appdir: '/Applications'

brew 'ack'
brew 'awscli'
brew 'ctags'
brew 'cmake'
brew 'gist'
brew 'git'
brew 'gnupg2'
brew 'graphviz'
brew 'heroku-toolbelt'
brew 'hub'
brew 'htop-osx'
brew 'imagemagick'
brew 'macvim'
brew 'mutt'
brew 'node'
brew 'openssl'
brew 'postgresql', args: ['with-python']
brew 'phantomjs'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tmux-cssh'
brew 'z'
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'zsh-completions'

brew 'rbenv'
brew 'ruby-build'
brew 'rbenv-binstubs'
brew 'rbenv-default-gems'

tap 'caskroom/cask'

cask 'arduino'
cask 'atom'
cask 'audacity'
cask 'bowtie'
cask 'clipmenu'
cask 'colloquy'
cask 'diffmerge'
cask 'docker'
cask 'hammerspoon'
cask 'hipchat'
cask 'intellij-idea'
cask 'jd-gui'
cask 'joinme'
cask 'kindle'
cask 'seil'
cask 'send-to-kindle'
cask 'sketch'
cask 'skype'
cask 'snagit'
cask 'spotify'
cask 'the-unarchiver'
cask 'virtualbox'
cask 'vagrant'
cask 'vlc'
